INFO:werkzeug:[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:10000
 * Running on http://172.27.0.4:10000
INFO:werkzeug:[33mPress CTRL+C to quit[0m
INFO:service:None
INFO:service:('f0128850-5423-43ec-96ee-bf1f500d3f3b',)
INFO:werkzeug:172.27.0.1 - - [09/Dec/2023 06:06:31] "POST /login HTTP/1.1" 200 -
INFO:service:('f0128850-5423-43ec-96ee-bf1f500d3f3b',)
INFO:service:WTF???
INFO:service:('f0128850-5423-43ec-96ee-bf1f500d3f3b',)
INFO:service:('f0128850-5423-43ec-96ee-bf1f500d3f3b',)
INFO:service:salt_f0128850-5423-43ec-96ee-bf1f500d3f3b
INFO:service:xc2gAEjnHdj8XBx5
INFO:service:xc2gAEjnHdj8XBx5
INFO:werkzeug:172.27.0.1 - - [09/Dec/2023 06:06:35] "GET /confirm HTTP/1.1" 200 -
INFO:service:0
INFO:service:<Request 'http://localhost:10000/profile' [GET]>
INFO:service:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiYzgyZGZhNzUtMDc3Ni00MzBmLWExMDMtYzhhN2ZlZjhhMDMyIn0.eqWEkkRJp_aTzcEyWX5IF1VIkNyDQoFMeRpBM8ohLtU
INFO:werkzeug:172.27.0.1 - - [09/Dec/2023 06:06:42] "[31m[1mGET /profile HTTP/1.1[0m" 401 -
INFO:service:0
INFO:service:<Request 'http://localhost:10000/profile' [GET]>
INFO:service:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1dWlkIjoiZjAxMjg4NTAtNTQyMy00M2VjLTk2ZWUtYmYxZjUwMGQzZjNiIn0.u-Je93zUAX1oDCO5IHZ3if42LIZhRZZNWBE0Q_JcDDo
INFO:service:f0128850-5423-43ec-96ee-bf1f500d3f3b
INFO:service:xc2gAEjnHdj8XBx5
ERROR:mainloop:Exception on /profile [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/app/src/mainloop.py", line 56, in wrapper
    return func(uuid)
  File "/app/src/mainloop.py", line 89, in ProfileHandler
    return Profile(uuid)
  File "/app/src/handlers/profile.py", line 23, in Profile
    user_data = get_user_by_uuid(uuid)
  File "/app/src/handlers/profile.py", line 8, in get_user_by_uuid
    logging.getLogger('service').info(uuid)
NameError: name 'logging' is not defined
INFO:werkzeug:172.27.0.1 - - [09/Dec/2023 06:06:53] "[35m[1mGET /profile HTTP/1.1[0m" 500 -
